### ISSUE TITLE
Non-Civic Match has both SITE_NAME.partialMatch and OCCUPANT_NAME.partialMatch faults

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-devkit#58] opened 2017-05-09 00:16 UTC
Example: 
https://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.xhtml?minScore=50&maxResults=10&addressString=PRINCE+RUPERT+LAW+COURTS--

Matches to "Prince Rupert Airport -- Digby Island, BC" with doubly-penalized partial name matches.

**Comment by cmhodgson** [comment] 2017-05-23 16:06
I suggest we close this as it is a duplicate of api-specs/201 and requires no work within the devkit to fix.

**Comment by mraross** [comment] 2017-05-23 17:47
Duplicate of https://github.com/bcgov/api-specs/issues/201

**Closed by mraross** 2017-05-23 17:47 UTC
Labels: bug, medium priority
